name: Update Protocol Buffers

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build on'
        required: true
        default: 'main'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Install Protoc
      uses: arduino/setup-protoc@v3
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    - name: Build ProtoBufs and update spec
      env:
        # GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p protos/gen
        GITHUB_ACCESS_TOKEN=${{ secrets.GH_TOKEN }} python3 fetch_protos.py
        git config user.email "actions@users.noreply.github.com"
        git config user.name "Protobuf Updater"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git add protos/
        git diff --quiet || git commit -m "Updating protocol buffers"
        git push origin ${{ github.event.inputs.branch }} -q