name: Update API spec

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'main'

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        pip install black
    - name: Clone and build
      run: |
        git clone https://github.com/signalapp/Signal-Server.git --depth=1 server
        cp -r server/* $(pwd)
        cp -r server/.mvn $(pwd)
    - name: Set up JDK  21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven' # This caches Maven dependencies
    - name: Build OpenAPI spec
      run: |
        ./mvnw compile
    - name: Update API stub
      env:
        # GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        cp -r api-doc/target/openapi/signal-server-openapi.yaml $(pwd)
        python3 parse_spec.py
        black server_proto.py
        git config user.email "actions@users.noreply.github.com"
        git config user.name "API Updater"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git add server_proto.py
        git diff --quiet || git commit -m "Updating server API"
        git push origin ${{ github.event.inputs.branch }} -q